### ISSUE TITLE
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "gamification_invento...

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#331]
https://sentry.io/gorails/gorails/issues/396735053/

```
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "gamification_inventories_pkey"
DETAIL:  Key (id)=(3521) already exists.

  app/observers/user_observer.rb:31:in `block in create_default_inventory'
    Gamification::Inventory.create(user_id: user.id, gamification_item_id: item.id, equipped: true)
  app/observers/user_observer.rb:30:in `create_default_inventory'
    default_inventory.items.each do |item|
  app/observers/user_observer.rb:24:in `after_create'
    create_default_inventory(user)
...
(164 additional frame(s) were not displayed)

ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "gamification_inventories_pkey"
DETAIL:  Key (id)=(3521) already exists.
: INSERT INTO "gamification_inventories" ("user_id", "gamification_item_id", "equipped", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"

ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "gamification_inventories_pkey"
DETAIL:  Key (id)=(3521) already exists.
: INSERT INTO "gamification_inventories" ("user_id", "gamification_item_id", "equipped", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"
```

**Comment by jcottobboni** [comment]
estava com erro na sequence. coloquei o valor correto esta ok agora
